from datetime import datetime

from jinja2 import Template
from weasyprint import HTML

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; color: #1a1a2e; margin: 40px; }
  .header { background: #0a1628; color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px; }
  .header h1 { margin: 0; font-size: 28px; }
  .header p { margin: 5px 0 0; color: #7eb8f7; }
  .section { margin-bottom: 25px; }
  .section h2 { color: #1B4F8A; border-bottom: 2px solid #2563EB; padding-bottom: 8px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }
  .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; }
  .price { font-size: 32px; font-weight: bold; color: #2563EB; }
  .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; background: #dbeafe; color: #1d4ed8; }
  .amenity { display: inline-block; padding: 3px 8px; background: #f1f5f9; border-radius: 4px; margin: 2px; font-size: 12px; }
  .footer { margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px; border-top: 1px solid #e2e8f0; padding-top: 20px; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #1B4F8A; color: white; padding: 10px; text-align: left; }
  td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }
  tr:nth-child(even) { background: #f8fafc; }
</style>
</head>
<body>
<div class="header">
  <h1>🏡 Property Intelligence Report</h1>
  <p>Generated by ARIA — {{ date }}</p>
</div>
<div class="section">
  <h2>Property Overview</h2>
  <span class="badge">{{ (property.property_type or "property") | upper }}</span>
  <span class="badge" style="background:#dcfce7;color:#166534">{{ (property.category or "listing") | upper }}</span>
  <h3 style="margin-top:10px">{{ property.title or "Untitled listing" }}</h3>
  <p class="price">{{ property.currency or "EUR" }} {{ "{:,.0f}".format(property.price) if property.price else "Price on Request" }}</p>
  <p>{{ property.description or "" }}</p>
</div>
<div class="section">
  <h2>Property Details</h2>
  <div class="grid">
    <div class="card"><strong>Bedrooms:</strong> {{ property.bedrooms or "—" }}</div>
    <div class="card"><strong>Bathrooms:</strong> {{ property.bathroom_count or "—" }}</div>
    <div class="card"><strong>Total Size:</strong> {{ property.total_sqm or "—" }} m²</div>
    <div class="card"><strong>Price per m²:</strong> {{ "{:,.0f}".format(property.price_per_sqm) if property.price_per_sqm else "—" }}</div>
    <div class="card"><strong>Floor:</strong> {{ property.floor_number or "—" }}</div>
    <div class="card"><strong>Year Built:</strong> {{ property.year_built or "—" }}</div>
  </div>
</div>
<div class="section">
  <h2>Location</h2>
  <p>📍 {{ property.locality or "" }}, {{ property.district or "" }}, {{ property.city or "" }}, {{ property.country or "" }}</p>
  {% if property.full_address %}<p>{{ property.full_address }}</p>{% endif %}
</div>
{% if property.amenities %}
<div class="section">
  <h2>Amenities</h2>
  {% for amenity in property.amenities %}
    <span class="amenity">{{ amenity }}</span>
  {% endfor %}
</div>
{% endif %}
{% if pricing_data %}
<div class="section">
  <h2>Market Analysis — {{ property.locality or "Area" }}</h2>
  <table>
    <tr><th>Metric</th><th>This Property</th><th>Area Average</th></tr>
    <tr><td>Price per m²</td><td>{{ "{:,.0f}".format(property.price_per_sqm) if property.price_per_sqm else "—" }}</td><td>{{ "{:,.0f}".format(pricing_data.avg_price_per_sqm) if pricing_data.avg_price_per_sqm else "—" }}</td></tr>
    <tr><td>Property Size</td><td>{{ property.total_sqm or "—" }} m²</td><td>{{ pricing_data.avg_size or "—" }} m²</td></tr>
  </table>
</div>
{% endif %}
{% if agency %}
<div class="section">
  <h2>Listed By</h2>
  <div class="grid">
    <div class="card">
      <strong>Agency:</strong> {{ agency.name }}<br>
      {% if agency.owner_name %}<p>Owner: {{ agency.owner_name }}</p>{% endif %}
      {% if agency.phone %}<p>📞 {{ agency.phone[0] if agency.phone }}</p>{% endif %}
      {% if agency.email %}<p>✉️ {{ agency.email[0] if agency.email }}</p>{% endif %}
    </div>
    <div class="card">
      <strong>Rating:</strong> ⭐ {{ agency.google_rating or "—" }}<br>
      {% if agency.website_url %}<p>🌐 {{ agency.website_url }}</p>{% endif %}
    </div>
  </div>
</div>
{% endif %}
<div class="footer">
  <p>Report generated by ARIA Real Estate Intelligence Platform</p>
  <p>Data sourced from agency websites and market analysis</p>
</div>
</body>
</html>
"""


async def generate_property_pdf(
    property_data: dict,
    agency_data: dict | None = None,
    pricing_data: dict | None = None,
) -> bytes:
    template = Template(REPORT_TEMPLATE)
    html_content = template.render(
        property=property_data,
        agency=agency_data,
        pricing_data=pricing_data,
        date=datetime.now().strftime("%B %d, %Y"),
    )
    return HTML(string=html_content).write_pdf()
